### ISSUE TITLE
Elegir framework de API

### ISSUE THREAD

**Issue by JuanLopez77** [ISCOUTB/AH-ProManage#10]

**Comment by LIA0822** [comment]
![Image](https://github.com/user-attachments/assets/8b3c7aa2-b83d-4cf5-9ab5-df08d0662add)

**Comment by jairoserrano** [comment]
porque lo eligieron?

**Comment by LIA0822** [comment]
FastAPI tiene un rendimiento extremadamente rápido gracias a su arquitectura asíncrona, permite crear y probar rápidamente los distintos endpoints de la API y La autogeneración de documentación con Swagger. También ofrece manejo avanzado de seguridad, incluyendo autenticación con OAuth2, JWT (JSON Web Tokens), y la encriptación de contraseñas.
