### ISSUE TITLE
Documentacion de API (swagger)

### ISSUE THREAD

**Issue by LIA0822** [ISCOUTB/AH-ProManage#14]

**Comment by LIA0822** [comment]
Documentacion de API  en swagger con algunas demostraciones, ya que todas siguen la misma estructura.

( Primera versión )
[Ejemplo_api - Swagger UI.pdf](https://github.com/user-attachments/files/17181411/Ejemplo_api.-.Swagger.UI.pdf)

**Comment by jairoserrano** [comment]
Adelante
