### ISSUE TITLE
Creacion de requerimientos funcionales y no funcionales

### ISSUE THREAD

**Issue by JuanLopez77** [ISCOUTB/AH-ProManage#3]

**Comment by JuanLopez77** [comment]
[requerimientos proyecto (1).docx](https://github.com/user-attachments/files/16930634/requerimientos.proyecto.1.docx)

**Comment by JuanLopez77** [comment]
3.1 Requerimientos funcionales.
1. El sistema debe permitir que los usuarios se registren e inicien sesión mediante un nombre de usuario o correo y una contraseña.
2. El sistema debe permitir la autenticación de dos factores (2FA).
3. El sistema debe permitir que los usuarios autenticados puedan crear, actualizar, eliminar y leer la información que se les autorice, según sus roles y permisos.
4. El sistema debe tener 3 estados de las tareas inicio, en progreso y finalizado.
5. El sistema debe permitir crear y gestionar tableros para diferentes proyectos.
6. El sistema debe permitir a los usuarios crear listas dentro de los tableros para organizar tareas.
7. El sistema debe permitir crear tarjetas dentro de las listas, representando las tareas o ítems de trabajo.
8. El sistema debe permitir arrastrar y soltar tarjetas entre listas para cambiar su estado o ubicación.
9. El sistema debe permitir establecer fechas límite para cada tarjeta.
10. El sistema debe permitir a los usuarios agregar descripciones y comentarios a las tarjetas para detallar la tarea.
11. El sistema debe permitir a los usuarios adjuntar archivos a las tarjetas, incluyendo documentos, imágenes y enlaces.
12. El sistema debe permitir la actualización de la información y cambios en tiempo real.
13. El sistema debe permitir exportar tableros, listas y tareas a formatos comunes como CSV o
 
3.2 Requerimientos no funcionales.
1. Los datos del usuario, las credenciales y cualquier otra información sensible, deben estar registrados en una base de datos segura.
2. La base de datos debe garantizar la integridad y disponibilidad de los datos, minimizando los riesgos de pérdida o corrupción.
3. El sistema debe utilizar cifrado para almacenar contraseñas y otros datos sensibles.
4. El sistema debe ser capaz de escalar para soportar un número creciente de usuarios y tareas sin degradar el rendimiento.
5. El sistema debe responder a las acciones del usuario en un tiempo razonable.
6. El sistema debe estar disponible asegurando que los usuarios puedan acceder al servicio cuando lo necesiten.
7. Deben implementarse medidas de recuperación ante desastres para minimizar el tiempo de inactividad en caso de fallos.
8. El sistema debe ser intuitivo y fácil de usar, con una interfaz de usuario clara y coherente.
9. El sistema debe permitir a los usuarios organizar las tareas según prioridad.
10. El sistema debe permitir a los usuarios recibir notificaciones en tiempo real sobre actualizaciones en los tableros más que todo en la creación y eliminación de tareas, una tarea próxima a vencer o ya vencida.
11. El sistema debe permitir a los usuarios etiquetar tareas con prioridades como alta, media o baja.
12. El sistema debe permitir establecer dependencias entre tarjetas, donde una tarea no puede comenzar hasta que otra esté completada.

**Comment by jairoserrano** [comment]
esto deben las historias de usuario en este punto
