### ISSUE TITLE
Historias de usuario y tareas relacionadas

### ISSUE THREAD

**Issue by JuanLopez77** [ISCOUTB/AH-ProManage#4]

**Comment by JuanLopez77** [comment]
**Historia de usuario**
➢ Descripción: Como usuario, quiero gestionar proyectos y sus diversas tareas de manera eficiente para mantener un seguimiento claro y organizado de mis actividades y cumplir con el objetivo de completarlo.
Criterios de Aceptación:
•	El tablero de proyectos debe mostrar todas las tareas en columnas de inicio, en progreso, y finalizado.
•	El usuario debe poder arrastrar y soltar tareas entre columnas.
•	El tablero debe actualizarse en tiempo real cuando se realicen cambios.
•	Cada tarea debe mostrar su estado, persona asignada, y fecha límite.
•	Debe existir la posibilidad de agregar nuevas tareas directamente desde el tablero.

 Tareas Relacionadas

•	Crear un mockup del tablero que muestre las columnas y la funcionalidad requerida.
•	Desarrollar el frontend del tablero para construir la interfaz de usuario, asegurando que sea intuitiva y fácil de usa
•	Conectar el tablero con la base de datos utilizando una API RESTful para cargar,
•	actualizar y eliminar tareas en tiempo real.
•	Implementar la funcionalidad para mostrar tareas en las columnas correspondientes.
•	Desarrollar la función de arrastrar y soltar tareas entre columnas.
•	Implementar actualizaciones en tiempo real en el tablero.
•	Diseñar la interfaz para mostrar el estado, asignado, y fecha límite de cada tarea.
•	Añadir la funcionalidad para crear nuevas tareas directamente desde el tablero.

➢ Descripción: Como usuario, quiero recibir notificaciones en tiempo real sobre
actualizaciones en las tareas para estar al tanto de los cambios y cumplir con mis
responsabilidades.

Criterios de Aceptación:
•	El sistema debe enviar notificaciones en tiempo real cuando se actualice el estado de una tarea asignada.
•	Las notificaciones deben incluir detalles como el nuevo estado, la persona que hizo el cambio, y la fecha de actualización.

Tareas Relacionadas:
•	Implementar un sistema de notificaciones en tiempo real para actualizaciones de tareas.
•	Desarrollar la interfaz para configurar preferencias de notificación.
•	Asegurar que las notificaciones incluyan toda la información relevante sobre los cambios en las tareas.

➢ Descripción: Como usuario, quiero poder adjuntar archivos a las tareas para proporcionar contexto adicional y recursos necesarios para la finalización de las tareas.

Criterios de Aceptación:
•	El sistema debe permitir a los usuarios adjuntar diferentes tipos de archivos a las tareas (documentos, imágenes, enlaces).
•	Los archivos adjuntos deben ser accesibles
•	El sistema debe permitir eliminar o reemplazar archivos adjuntos.

Tareas Relacionadas:
•	Implementar la funcionalidad para adjuntar archivos a las tareas.
•	Desarrollar la interfaz para visualizar y acceder a los archivos adjuntos desde las tareas.
•	Asegurar que los archivos adjuntos puedan ser eliminados o reemplazados según sea necesario.

➢ Descripción: Como usuario, quiero exportar tableros y listas a formatos como CSV o PDF para compartir el progreso del proyecto con otros interesados fuera del sistema.

Criterios de Aceptación:
•	El sistema debe permitir exportar los datos de los tableros y listas a formatos CSV y PDF.
•	La exportación debe incluir todos los detalles de las tareas (estado, asignado, fecha límite).
•	Los archivos exportados deben ser descargables y accesibles por cualquier usuario con los permisos adecuados.

 Tareas Relacionadas:
•	Desarrollar la funcionalidad para exportar tableros y listas en formato CSV y PDF.
•	Asegurar que los archivos exportados incluyan toda la información relevante de las tareas.
•	Implementar opciones de descarga para los archivos exportados.

**Comment by jairoserrano** [comment]
falta la creación de tareas como issues.
