### ISSUE TITLE
Modelo de datos con SQL y NOSQL

### ISSUE THREAD

**Issue by JuanLopez77** [ISCOUTB/AH-ProManage#5]

**Comment by JuanLopez77** [comment]
**Modelado de datos E-R ProManage**

![Image](https://github.com/user-attachments/assets/85bdf368-b34f-40fe-b21b-9731acac4c9e)

**Modelado de datos no relacional documentos ProManage**

![Image](https://github.com/user-attachments/assets/db30ff55-7f53-4347-a267-161eb88963dc)

**Comment by jairoserrano** [comment]
Muy buen acercamiento al modelado de NoSQL y Relacional.
Traten de "aplanar" un poco más las respuestas, entidades, detalles y vinculos.
