### ISSUE TITLE
Elegir motor DB

### ISSUE THREAD

**Issue by JuanLopez77** [ISCOUTB/AH-ProManage#6]

**Comment by JuanLopez77** [comment]
Motor Posgrest
MongoDB

**Comment by JuanLopez77** [comment]
**PostgreSQL**
![Image](https://github.com/user-attachments/assets/db9bf418-455d-46aa-abd2-63b6995c1e2c)

Este motor de base de datos nos permite administrar nuestras bases de datos de forma fácil e intuitiva. Podemos ejecutar sentencias SQL, e incluso crear copias de seguridad o realizar tareas de mantenimiento.

**MongoDB**

![Image](https://github.com/user-attachments/assets/942e8616-f213-49ff-9b99-8e255e075928)

Este motor nos permite definir y adherirnos a la estructura predefinida de los datos entrantes, trabajar con datos no estructurados y semiestructurados ya que almacena cada registro individual en documentos de tipo JSON que pueden variar en sus estructuras y su esquema se puede cambiar

**Comment by jairoserrano** [comment]
Seleccionado entonces. procedan a buscar qué imágenes y versiones de docker les funcionará.
