### ISSUE TITLE
Creacion de la base de datos

### ISSUE THREAD

**Issue by JuanLopez77** [ISCOUTB/AH-ProManage#9]

**Comment by LIA0822** [comment]
Plataforma de despliegue Railway: https://railway.app/

Ofrece una configuración automática del entorno, integración directa con GitHub, soporte para bases de datos PostgreSQL y tambien monitoreo en tiempo real

![Image](https://github.com/user-attachments/assets/388d02b0-84b8-407c-98cd-3849ff4dbad6)
